python anima_minimal_inference.py \
  --dit /root/autodl-tmp/ComfyUI/models/diffusion_models/anima-base-v1.0.safetensors \
  --vae /root/autodl-tmp/ComfyUI/models/vae/qwen_image_vae.safetensors \
  --text_encoder /root/autodl-tmp/ckn/qwen3 \
  --prompt "你的提示词" \
  --image_size 1024 1024 \
  --reference_image /root/autodl-tmp/ckn/test/ref.png \
  --save_path out/infer.png \
  --lora_weight out/anima_multi_ipadapter_self_ref_overfit-step00000500.safetensors \
  --lora_multiplier 1.0 \
  --ip_adapter \
  --omni-adapter \
  --ip_adapter_weight out/anima_multi_ipadapter_self_ref_overfit-step00000500_ip_adapter.safetensors \
  --ip_adapter_feature_backend ccip_tokens \
  --ip_adapter_feature_model /root/autodl-tmp/ckn/ccip_model/ccip-caformer_b36-24.ckpt \
  --infer_steps 50 \
  --guidance_scale 3.5